Debug "0"

# A more correct way of passing sample rate to pw-play would be:
#   --rate \$(jq .audio.sample_rate < /opt/piper-tts/voices/\$VOICE.onnx.json)
#   GenericCmdDependency "jq"

# It is possible to implement $PITCH control by:
#   varying --rate to change voice pitch and tempo
#   varying --length_scale to restore correct tempo

# The variables below are single-quoted because they are actually just tokens which will be substituted with constants.
# Therefore it is not possible to use curly braces ${VAR} on them and therefore expr must be used instead!

# Executable configuration:
#GenericExecuteSynth "printf %s \'$DATA\' | piper-tts --sentence_silence 0.1 --model \'/usr/share/piper-voices/$VOICE\' --length_scale $(echo \'scale=2; 1.33/($RATE + .66)\' | bc) --output_raw | pw-play --volume $(echo \'scale=2; $VOLUME/100\' | bc) --rate $( [ \"$(expr substr \'$VOICE\' $(expr length \'$VOICE\' - 7) 3)\" = low ] && echo 16000 || echo 22050 ) --media-role=Text-To-Speech --channel-map mono -"
# GenericExecuteSynth "echo \'$DATA\' | piper-tts --sentence_silence 0.1 --model /usr/share/piper-voices/$VOICE --length_scale $(echo \'scale=2; 1.33/($RATE + .66)\' | bc) -f - | pw-play --volume $(echo \'scale=2; $VOLUME/100\' | bc) --media-role=Text-To-Speech --channel-map mono -"
GenericExecuteSynth "echo \'$DATA\' | piper-tts --sentence_silence 0.1 --model /usr/share/piper-voices/$VOICE --length_scale $(echo \'scale=2; 1.33/($RATE + .66)\' | bc) --volume $(echo \'scale=2; $VOLUME/100\' | bc)"
# GenericExecuteSynth "echo \'$DATA\' | piper-tts --model /usr/share/piper-voices/$VOICE | pw-play --volume=0.8 --media-role=Text-To-Speech --channel-map=mono - "
GenericCmdDependency "piper-tts"
# GenericCmdDependency "pw-play"
GenericCmdDependency "bc"


# Prevent speech-dispatcher from cutting text into chunks:
#GenericDelimiters "|"  # "|" never occurs
#GenericMaxChunkLength 99999

GenericRateAdd 1
# GenericPitchAdd 1
# GenericVolumeAdd 1
GenericRateMultiply 1
GenericPitchMultiply 1000

# Ensure all characters will be interpreted and spoken:
GenericLanguage "en" "en-US" "utf-8"
GenericLanguage "en-gb" "en-GB" "utf-8"
GenericLanguage "hu" "hu-HU" "utf-8"
GenericLanguage "hu-HU" "hu-HU" "utf-8"

VoiceFileDependency "/usr/share/piper-voices/$VOICE"
AddVoice "en-GB" "FEMALE1" "en_GB-alba-medium.onnx"
AddVoice "hu-HU" "FEMALE1" "hu_HU-anna-medium.onnx"
DefaultVoice "en_GB-alba-medium.onnx"
